server:
  port: 8166

spring:
  datasource:
    url: jdbc:mysql://47.94.59.49:3306/qixiu?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    password: aSbjyCG4XCHT6LFe
    username: qixiu
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  type-aliases-package: com.example.car.model.pojos
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true